# Generated by Django 6.1 on 2026-08-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='file_context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
