# Generated by Django 6.1 on 2026-08-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_learningsession_file_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='learning_gaps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
    ]
