# Generated by Django 6.1 on 2026-08-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aiweekendlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiweekendlead',
            name='email_1_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiweekendlead',
            name='email_2_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiweekendlead',
            name='email_3_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiweekendregistration',
            name='access_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
