# Generated by Django 6.1 on 2026-08-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_aiweekendlead_email_1_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiweekendregistration',
            name='meeting_link_sent',
            field=models.BooleanField(default=False),
        ),
    ]
